ib_connections:
  - name: "ib-local"
    address: "127.0.0.1:4040"
    client_id: 1
  - name: "ib-local-2"
    address: "127.0.0.1:4050"
    client_id: 2

brokers:
  - name: "ib-broker"
    type: "IbBroker"
    params:
      connection: "IB-local"
  - name: "dummy-broker"
    type: "DummyBroker"

sizers:
  - name: "fixed-100"
    type: "FixedSizer"
    params:
      qty: 100
  - name: "equity-10"
    type: "PercentOfEquitySizer"
    params:
      percent: 0.1

data_feeds:
  - name: "backetest-data-feed"
    type: "CsvDataFeed"
    params:
      path: "test/csv_data_1.csv"
  - name: "ib-market-data-feed"
    type: "IbMarketDataFeed"
    params:
      connection: "ib-local"
  - name: "ib-historical-data-feed"
    type: "IbHistoricalDataFeed"
    params:
      connection: "ib-local-2"

strategies:
  - name: "print-a"
    type: "PrintStrategy"
    broker: "dummy-broker"
    data_feed: "backtest-data-feed"
    sizer: "fixed-100"
  - name: "sma-cross-historical-data"
    type: "SmaCrossStrategy"
    broker: "dummy-broker"
    data_feed: "ib-historical-data-feed"
    sizer: "equity-10%"
    params:
      slow_window: 200
      fast_window: 50
  - name: "sma-cross-market-data"
    type: "SmaCrossStrategy"
    broker: "dummy-roker"
    data_feed: "ib-market-data-feed"
    sizer: "equity-10%"
    params:
      slow_window: 200
      fast_window: 50